import csv
from collections import defaultdict

from classify import TYPES, classify, build_building_overrides

CSV_PATH = "room_metadata.csv"
OUT_PATH = "room_type_updates.sql"
CHUNK_SIZE = 1000


def build_campus_company_map(rows):
    mapping = {}
    for row in rows:
        campus = row["campus_id"].strip()
        company = row["company_id"].strip()
        if campus and company:
            mapping[campus] = company
    return mapping


def chunks(seq, size):
    for i in range(0, len(seq), size):
        yield seq[i:i + size]


def sql_quote(value):
    return "'" + value.replace("'", "''") + "'"


def main():
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    valid_types = set(TYPES)
    building_overrides = build_building_overrides(rows, valid_types)
    campus_company = build_campus_company_map(rows)

    # group[(type_id, type_name, profile, company_id_or_None)] -> list of room_metadata.id
    groups = defaultdict(list)
    stats = {"already_classified_kept": 0, "reclassified": 0, "company_filled": 0,
             "company_unknown": 0}

    for row in rows:
        existing_type = row["entity_room_type_name"].strip()
        if existing_type in valid_types:
            type_name = existing_type
            stats["already_classified_kept"] += 1
        else:
            type_name = classify(row["room_name"], row["department_name"],
                                  row["building_id"], building_overrides)
            stats["reclassified"] += 1

        type_id, profile = TYPES[type_name]

        existing_company = row["company_id"].strip()
        if existing_company:
            company_id = existing_company
        else:
            company_id = campus_company.get(row["campus_id"].strip())
            if company_id:
                stats["company_filled"] += 1
            else:
                stats["company_unknown"] += 1

        key = (type_id, type_name, profile, company_id)
        groups[key].append(row["id"])

    print("stats:", stats)
    print("groups:", len(groups))

    statement_count = 0
    with open(OUT_PATH, "w", encoding="utf-8") as out:
        out.write("-- Generated by generate_sql.py from room_metadata.csv\n")
        out.write("-- Classifies rooms into the 8 categories from room_types.json and\n")
        out.write("-- backfills the new room_type_profile column plus company_id where derivable\n")
        out.write("-- from the room's campus_id (only known for campuses that already had it set).\n\n")

        for (type_id, type_name, profile, company_id), ids in sorted(groups.items(), key=lambda kv: kv[0][1]):
            for chunk in chunks(ids, CHUNK_SIZE):
                id_list = ", ".join(chunk)
                set_clauses = [
                    f"entity_room_type_id = {sql_quote(type_id)}",
                    f"entity_room_type_name = {sql_quote(type_name)}",
                    f"room_type_profile = {sql_quote(profile)}",
                ]
                if company_id:
                    set_clauses.append(f"company_id = {sql_quote(company_id)}")
                out.write(
                    f"UPDATE room_metadata SET {', '.join(set_clauses)} "
                    f"WHERE id IN ({id_list});\n"
                )
                statement_count += 1

    print("statements written:", statement_count)
    print("output:", OUT_PATH)


if __name__ == "__main__":
    main()
