"""Generate the two SQL scripts needed by the TimescaleDB target:

1. staff_role_dictionary.sql   - CREATE TYPE/TABLE + population for the raw
   `staff_role` free-text value -> canonical healthcare_role dictionary.
2. entity_healthcare_role_map.sql - CREATE TABLE + population for the
   entity_id -> healthcare_role lookup the target db actually needs
   (it only has entity_id, not the raw staff_role text).

Both derive from the same classify_staff_role.classify() function so the two
tables are always consistent with each other and with staff_role_classification.csv.
"""

import pyarrow.parquet as pq
import pyarrow.compute as pc

from classify_staff_role import classify, CASCADE

SRC = "hca_entities_light.parquet"
DICT_SQL_PATH = "staff_role_dictionary.sql"
MAP_SQL_PATH = "entity_healthcare_role_map.sql"
BATCH_SIZE_DICT = 500

ROLE_CODES = sorted({role for _b, role, _t in CASCADE} | {"ALLIED_HEALTH"})

ROLE_DESCRIPTIONS = {
    "EVS": "Environmental Services - housekeeping/custodial staff responsible for "
           "facility cleaning and sanitation.",
    "BIOMED": "Biomedical Engineering - technicians who install, maintain, and repair "
              "clinical/medical equipment.",
    "PROVIDER": "Clinical provider delivering direct patient care - physicians, "
                "hospitalists, residents, and advanced practice providers (NP/PA/CRNA).",
    "SUPPLY_CHAIN_TECH": "Supply chain / materials management - staff handling medical "
                         "supplies, sterile processing, and logistics.",
    "MA": "Medical Assistant - clinical and administrative support staff working under "
          "a provider's supervision, typically in ambulatory/clinic settings.",
    "RN": "Registered Nurse - licensed nursing staff providing direct patient care, "
          "including nursing students/externs in training.",
    "TECH": "Technician/assistant-tier clinical support staff (patient care tech, CNA, "
            "lab assistant, phlebotomist, monitor tech, etc.) working under supervision "
            "of licensed clinicians.",
    "SECURITY": "Facility security and law enforcement staff (security officers, police "
                "officers) responsible for site safety.",
    "NON_CLINICAL": "Administrative, clerical, and facility support staff who do not "
                    "provide or assist with direct clinical care (registrars, "
                    "schedulers, billing/coding, food service, volunteers, vendors, "
                    "students, contractors).",
    "ALLIED_HEALTH": "Independently-licensed clinical professionals outside the "
                     "physician/nursing tracks (pharmacists, social workers, "
                     "dietitians, physical/occupational therapists, speech-language "
                     "pathologists).",
}

assert set(ROLE_CODES) == set(ROLE_DESCRIPTIONS), (
    set(ROLE_CODES) ^ set(ROLE_DESCRIPTIONS)
)


def sql_str(value):
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def chunks(seq, size):
    for i in range(0, len(seq), size):
        yield seq[i:i + size]


def write_dictionary_sql(staff_roles):
    """staff_roles: dict[str raw_value] -> count (from source data)."""
    rows = []
    for raw_value, count in staff_roles.items():
        role = classify(raw_value)
        rows.append((raw_value, role, count))
    rows.sort(key=lambda r: -r[2])

    with open(DICT_SQL_PATH, "w", encoding="utf-8") as out:
        out.write("-- Generated by generate_role_mapping_sql.py\n")
        out.write("-- Dictionary: raw 'Staff Role' free-text value -> canonical healthcare_role.\n")
        out.write("-- healthcare_role/description are NULL where the source value has no\n")
        out.write("-- confident mapping (e.g. EHR access-tier placeholders, blank values).\n\n")

        out.write("CREATE TYPE healthcare_role AS ENUM (\n    ")
        out.write(",\n    ".join(sql_str(r) for r in ROLE_CODES))
        out.write("\n);\n\n")

        out.write("CREATE TABLE staff_role_dictionary (\n"
                   "    staff_role_raw    TEXT PRIMARY KEY,\n"
                   "    healthcare_role   healthcare_role,\n"
                   "    description       TEXT,\n"
                   "    source_row_count  INTEGER\n"
                   ");\n\n")

        out.write("CREATE INDEX idx_staff_role_dictionary_healthcare_role\n"
                   "    ON staff_role_dictionary (healthcare_role);\n\n")

        stmt_count = 0
        for batch in chunks(rows, BATCH_SIZE_DICT):
            values = []
            for raw_value, role, count in batch:
                description = ROLE_DESCRIPTIONS.get(role)
                values.append(
                    f"({sql_str(raw_value)}, {sql_str(role)}, {sql_str(description)}, {count})"
                )
            out.write(
                "INSERT INTO staff_role_dictionary "
                "(staff_role_raw, healthcare_role, description, source_row_count) VALUES\n"
            )
            out.write(",\n".join(values))
            out.write(";\n\n")
            stmt_count += 1

    print(f"{DICT_SQL_PATH}: {len(rows)} rows, {stmt_count} INSERT statements")


def copy_csv_field(value):
    """CSV-format COPY quoting: NULL is a bare empty field (no quotes); every other
    value - including a real empty string - is quoted, so "" and NULL stay distinguishable."""
    if value is None:
        return ""
    escaped = str(value).replace('"', '""')
    return f'"{escaped}"'


def write_entity_map_sql(entity_rows):
    """entity_rows: list of (entity_id, status, staff_role, company_id).

    Uses COPY ... FROM STDIN instead of batched INSERTs - at 1.1M rows this loads in
    a fraction of the time and produces a much smaller file. Only psql (or another
    client implementing the same COPY protocol) can run this; see README.md.
    """
    with open(MAP_SQL_PATH, "w", encoding="utf-8") as out:
        out.write("-- Generated by generate_role_mapping_sql.py\n")
        out.write("-- entity_id -> healthcare_role lookup for PERSON entities (template_reference.profileType = 'PERSON').\n")
        out.write("-- Resolved via the same classify_staff_role.classify() logic as staff_role_dictionary,\n")
        out.write("-- so this can also be derived with:\n")
        out.write("--   SELECT e.entity_id, d.healthcare_role FROM entity_staff_role e\n")
        out.write("--   LEFT JOIN staff_role_dictionary d ON d.staff_role_raw = e.staff_role;\n")
        out.write("-- healthcare_role is NULL when the entity had no staff_role attribute or it\n")
        out.write("-- didn't map to a known role (see staff_role_dictionary for the raw value).\n")
        out.write("-- Run via `psql -f entity_healthcare_role_map.sql` (or `\\i` inside psql) - see README.md.\n\n")

        out.write("CREATE TABLE entity_healthcare_role_map (\n"
                   "    entity_id        TEXT PRIMARY KEY,\n"
                   "    status           TEXT,\n"
                   "    healthcare_role  healthcare_role,\n"
                   "    company_id       TEXT\n"
                   ");\n\n")

        out.write("COPY entity_healthcare_role_map (entity_id, status, healthcare_role, company_id) "
                   "FROM STDIN WITH (FORMAT csv);\n")
        for entity_id, status, staff_role, company_id in entity_rows:
            role = classify(staff_role)
            fields = (copy_csv_field(entity_id), copy_csv_field(status),
                      copy_csv_field(role), copy_csv_field(company_id))
            out.write(",".join(fields))
            out.write("\n")
        out.write("\\.\n\n")

        # Indexes are created after the bulk load - building them row-by-row during
        # COPY would slow the load down for no benefit.
        out.write("CREATE INDEX idx_entity_healthcare_role_map_role\n"
                   "    ON entity_healthcare_role_map (healthcare_role);\n\n")
        out.write("CREATE INDEX idx_entity_healthcare_role_map_company\n"
                   "    ON entity_healthcare_role_map (company_id);\n")

    print(f"{MAP_SQL_PATH}: {len(entity_rows)} rows via COPY FROM STDIN")


def main():
    t = pq.read_table(SRC)
    mask = pc.equal(t.column("template_reference_profile_type"), "PERSON")
    sub = t.filter(mask)
    cols = sub.select(["entity_id", "status", "staff_role", "company_id"]).to_pylist()

    staff_role_counts = {}
    entity_rows = []
    for row in cols:
        entity_rows.append((row["entity_id"], row["status"], row["staff_role"], row["company_id"]))
        if row["staff_role"] is not None:
            staff_role_counts[row["staff_role"]] = staff_role_counts.get(row["staff_role"], 0) + 1

    write_dictionary_sql(staff_role_counts)
    write_entity_map_sql(entity_rows)


if __name__ == "__main__":
    main()
